@baseUrl = http://localhost:3000

### Get Blogs
GET {{baseUrl}}/posts
Accept: application/json

### Create Blog

POST {{baseUrl}}/posts
Content-Type: application/json
authorization: Basic YWRtaW46cXdlcnR5

{
  "name": "string",
  "description": "string",
  "websiteUrl": "https://google.com"
}

### Get Blog by id
GET {{baseUrl}}/posts/0
Accept: application/json

### Update Blog by id
PUT {{baseUrl}}/posts/0
Content-Type: application/json

{
  "name": "string",
  "description": "string",
  "websiteUrl": "https://google.com"
}

### Delete Blog by id
DELETE {{baseUrl}}/posts/0
Content-Type: application/json
