export const TYPES = {
  Application: Symbol.for('Application'),
  ILogger: Symbol.for('ILogger'),
  ExceptionFilter: Symbol.for('ExceptionFilter'),
  VideosController: Symbol.for('VideosController'),
  VideosService: Symbol.for('VideosService'),
  VideosRepository: Symbol.for('VideosRepository'),
  UtilsController: Symbol.for('UtilsController'),
  BlogsController: Symbol.for('BlogsController'),
  BlogsService: Symbol.for('BlogsService'),
  BlogsRepository: Symbol.for('BlogsRepository'),
  PostsService: Symbol.for('PostsService'),
  PostsController: Symbol.for('PostsController'),
  AuthMiddlewareService: Symbol.for('AuthMiddlewareService'),
  MongoDBClient: Symbol.for('MongoDBClient'),
};
